import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

// `npm run dev` (watch mode) keeps a readable build with inline sourcemaps;
// `npm run build` type-checks first (tsc -noEmit), then minifies for release
const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/MichaBrugger/obsidian-footnotes
*/
`;

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
        ...builtinModules.map((m) => `node:${m}`),
    ],
    format: "cjs",
    // es2018, matching the official sample plugin: Android WebViews can lag
    // years behind (degoogled phones, e-ink readers — see issue #46), and
    // untranspiled ?. / ?? syntax makes the whole plugin fail to LOAD there
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
});

if (prod) {
    await context.rebuild();
    await context.dispose();
} else {
    await context.watch();
}
